/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    static String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(App.getGreeting());
    }
    public static int add(int a, int b) {return a+b;}
}
